import { IProductDto } from '../dtos/products.dto';

export const testProductsData: IProductDto[] = [
  {
    id: 1,
    title: 'iPhone 15 Pro',
    description:
      'A powerful smartphone with a titanium design and advanced camera system.',
    category: 'smartphones',
    price: 999,
    discountPercentage: 8.5,
    rating: 4.7,
    stock: 35,
    tags: ['smartphone', 'apple', 'iphone'],
    brand: 'Apple',
    sku: 'APL-IP15P-001',
    weight: 187,
    dimensions: {
      width: 7.1,
      height: 14.7,
      depth: 0.8,
    },
    warrantyInformation: '1 year Apple warranty',
    shippingInformation: 'Ships within 2 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'Excellent phone with a great camera.',
        date: '2026-08-10',
        reviewerName: 'Ali',
        reviewerEmail: 'ali@example.com',
      },
      {
        rating: 4,
        comment: 'Great performance and beautiful design.',
        date: '2026-08-15',
        reviewerName: 'Sara',
        reviewerEmail: 'sara@example.com',
      },
    ],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-01-10T10:00:00Z',
      updatedAt: '2026-08-10T10:00:00Z',
      barcode: '1234567890123',
      qrCode: 'https://example.com/qr/1',
    },
    images: [
      'https://example.com/images/iphone-15-pro-1.jpg',
      'https://example.com/images/iphone-15-pro-2.jpg',
    ],
    thumbnail: 'https://example.com/images/iphone-15-pro-thumb.jpg',
  },

  {
    id: 2,
    title: 'MacBook Air M3',
    description: 'A lightweight laptop powered by the Apple M3 chip.',
    category: 'laptops',
    price: 1199,
    discountPercentage: 6.25,
    rating: 4.8,
    stock: 20,
    tags: ['laptop', 'apple', 'macbook'],
    brand: 'Apple',
    sku: 'APL-MBA-M3-002',
    weight: 1240,
    dimensions: {
      width: 30.4,
      height: 21.5,
      depth: 1.1,
    },
    warrantyInformation: '1 year Apple warranty',
    shippingInformation: 'Ships within 3 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'Very fast and lightweight.',
        date: '2026-07-21',
        reviewerName: 'Reza',
        reviewerEmail: 'reza@example.com',
      },
    ],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-02-15T09:00:00Z',
      updatedAt: '2026-07-21T12:00:00Z',
      barcode: '2234567890123',
      qrCode: 'https://example.com/qr/2',
    },
    images: [
      'https://example.com/images/macbook-air-m3-1.jpg',
      'https://example.com/images/macbook-air-m3-2.jpg',
    ],
    thumbnail: 'https://example.com/images/macbook-air-m3-thumb.jpg',
  },

  {
    id: 3,
    title: 'Sony WH-1000XM5',
    description:
      'Wireless noise cancelling headphones with high quality sound.',
    category: 'audio',
    price: 349,
    discountPercentage: 10,
    rating: 4.6,
    stock: 48,
    tags: ['headphones', 'wireless', 'sony'],
    brand: 'Sony',
    sku: 'SNY-WHXM5-003',
    weight: 250,
    dimensions: {
      width: 18,
      height: 20,
      depth: 8,
    },
    warrantyInformation: '1 year Sony warranty',
    shippingInformation: 'Ships within 1 business day',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'The noise cancellation is fantastic.',
        date: '2026-06-18',
        reviewerName: 'Hamed',
        reviewerEmail: 'hamed@example.com',
      },
    ],
    returnPolicy: '14 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-03-05T08:30:00Z',
      updatedAt: '2026-06-18T15:00:00Z',
      barcode: '3234567890123',
      qrCode: 'https://example.com/qr/3',
    },
    images: [
      'https://example.com/images/sony-whxm5-1.jpg',
      'https://example.com/images/sony-whxm5-2.jpg',
    ],
    thumbnail: 'https://example.com/images/sony-whxm5-thumb.jpg',
  },

  {
    id: 4,
    title: 'Samsung Galaxy S25',
    description:
      'A modern Android smartphone with a powerful processor and advanced display.',
    category: 'smartphones',
    price: 899,
    discountPercentage: 12,
    rating: 4.5,
    stock: 42,
    tags: ['smartphone', 'android', 'samsung'],
    brand: 'Samsung',
    sku: 'SMS-S25-004',
    weight: 162,
    dimensions: {
      width: 7.1,
      height: 14.7,
      depth: 0.8,
    },
    warrantyInformation: '1 year Samsung warranty',
    shippingInformation: 'Ships within 2 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 4,
        comment: 'Great display and performance.',
        date: '2026-05-12',
        reviewerName: 'Mohammad',
        reviewerEmail: 'mohammad@example.com',
      },
    ],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-04-01T10:00:00Z',
      updatedAt: '2026-05-12T11:30:00Z',
      barcode: '4234567890123',
      qrCode: 'https://example.com/qr/4',
    },
    images: [
      'https://example.com/images/galaxy-s25-1.jpg',
      'https://example.com/images/galaxy-s25-2.jpg',
    ],
    thumbnail: 'https://example.com/images/galaxy-s25-thumb.jpg',
  },

  {
    id: 5,
    title: 'Nike Air Max 270',
    description: 'Comfortable lifestyle sneakers designed for everyday use.',
    category: 'shoes',
    price: 149,
    discountPercentage: 15,
    rating: 4.4,
    stock: 75,
    tags: ['shoes', 'sneakers', 'nike'],
    brand: 'Nike',
    sku: 'NKE-AM270-005',
    weight: 720,
    dimensions: {
      width: 12,
      height: 10,
      depth: 30,
    },
    warrantyInformation: '6 months manufacturer warranty',
    shippingInformation: 'Ships within 3 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 4,
        comment: 'Very comfortable for everyday use.',
        date: '2026-04-20',
        reviewerName: 'Kian',
        reviewerEmail: 'kian@example.com',
      },
    ],
    returnPolicy: '14 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-02-20T14:00:00Z',
      updatedAt: '2026-04-20T10:00:00Z',
      barcode: '5234567890123',
      qrCode: 'https://example.com/qr/5',
    },
    images: [
      'https://example.com/images/nike-air-max-270-1.jpg',
      'https://example.com/images/nike-air-max-270-2.jpg',
    ],
    thumbnail: 'https://example.com/images/nike-air-max-270-thumb.jpg',
  },
  {
    id: 6,
    title: 'Google Pixel 9 Pro',
    description:
      'A premium Google smartphone with an advanced camera and clean Android experience.',
    category: 'smartphones',
    price: 899,
    discountPercentage: 9.5,
    rating: 4.6,
    stock: 28,
    tags: ['smartphone', 'google', 'pixel'],
    brand: 'Google',
    sku: 'GGL-PX9P-006',
    weight: 199,
    dimensions: {
      width: 7.3,
      height: 15.2,
      depth: 0.9,
    },
    warrantyInformation: '1 year Google warranty',
    shippingInformation: 'Ships within 2 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'The camera quality is excellent.',
        date: '2026-07-15',
        reviewerName: 'Arman',
        reviewerEmail: 'arman@example.com',
      },
    ],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-03-10T10:00:00Z',
      updatedAt: '2026-07-15T11:00:00Z',
      barcode: '6234567890123',
      qrCode: 'https://example.com/qr/6',
    },
    images: [
      'https://avatar.iran.liara.run/public/16',
      'https://avatar.iran.liara.run/public/17',
    ],
    thumbnail: 'https://avatar.iran.liara.run/public/16',
  },

  {
    id: 7,
    title: 'Dell XPS 15',
    description:
      'A powerful premium laptop designed for productivity, development and creative work.',
    category: 'laptops',
    price: 1599,
    discountPercentage: 7,
    rating: 4.7,
    stock: 16,
    tags: ['laptop', 'dell', 'xps'],
    brand: 'Dell',
    sku: 'DLL-XPS15-007',
    weight: 1860,
    dimensions: {
      width: 34.4,
      height: 23,
      depth: 1.8,
    },
    warrantyInformation: '2 year Dell warranty',
    shippingInformation: 'Ships within 3 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'Excellent laptop for development.',
        date: '2026-06-25',
        reviewerName: 'Nima',
        reviewerEmail: 'nima@example.com',
      },
    ],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-02-18T09:00:00Z',
      updatedAt: '2026-06-25T13:00:00Z',
      barcode: '7234567890123',
      qrCode: 'https://example.com/qr/7',
    },
    images: [
      'https://avatar.iran.liara.run/public/18',
      'https://avatar.iran.liara.run/public/19',
    ],
    thumbnail: 'https://avatar.iran.liara.run/public/18',
  },

  {
    id: 8,
    title: 'Samsung Galaxy Watch 7',
    description:
      'A modern smartwatch with health tracking and fitness features.',
    category: 'smartwatch',
    price: 299,
    discountPercentage: 11,
    rating: 4.5,
    stock: 31,
    tags: ['smartwatch', 'samsung', 'wearable'],
    brand: 'Samsung',
    sku: 'SMS-W7-008',
    weight: 44,
    dimensions: {
      width: 4.4,
      height: 4.4,
      depth: 1,
    },
    warrantyInformation: '1 year Samsung warranty',
    shippingInformation: 'Ships within 2 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 4,
        comment: 'Good smartwatch with a bright display.',
        date: '2026-05-30',
        reviewerName: 'Omid',
        reviewerEmail: 'omid@example.com',
      },
    ],
    returnPolicy: '14 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-03-01T12:00:00Z',
      updatedAt: '2026-05-30T10:30:00Z',
      barcode: '8234567890123',
      qrCode: 'https://example.com/qr/8',
    },
    images: [
      'https://avatar.iran.liara.run/public/20',
      'https://avatar.iran.liara.run/public/21',
    ],
    thumbnail: 'https://avatar.iran.liara.run/public/20',
  },

  {
    id: 9,
    title: 'Apple AirPods Pro 2',
    description:
      'Wireless earbuds with active noise cancellation and immersive sound.',
    category: 'audio',
    price: 249,
    discountPercentage: 5,
    rating: 4.8,
    stock: 65,
    tags: ['airpods', 'apple', 'wireless', 'audio'],
    brand: 'Apple',
    sku: 'APL-APP2-009',
    weight: 51,
    dimensions: {
      width: 6,
      height: 4.5,
      depth: 2.1,
    },
    warrantyInformation: '1 year Apple warranty',
    shippingInformation: 'Ships within 1 business day',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'Amazing sound quality and noise cancellation.',
        date: '2026-08-01',
        reviewerName: 'Pouya',
        reviewerEmail: 'pouya@example.com',
      },
    ],
    returnPolicy: '14 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-03-20T08:00:00Z',
      updatedAt: '2026-08-01T14:00:00Z',
      barcode: '9234567890123',
      qrCode: 'https://example.com/qr/9',
    },
    images: [
      'https://avatar.iran.liara.run/public/22',
      'https://avatar.iran.liara.run/public/23',
    ],
    thumbnail: 'https://avatar.iran.liara.run/public/22',
  },

  {
    id: 10,
    title: 'PlayStation 5 Slim',
    description:
      'A compact gaming console with high performance and fast loading times.',
    category: 'gaming',
    price: 499,
    discountPercentage: 4,
    rating: 4.9,
    stock: 18,
    tags: ['gaming', 'console', 'playstation'],
    brand: 'Sony',
    sku: 'SNY-PS5S-010',
    weight: 3200,
    dimensions: {
      width: 8.9,
      height: 35.8,
      depth: 21.6,
    },
    warrantyInformation: '1 year Sony warranty',
    shippingInformation: 'Ships within 2 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'Excellent console with great performance.',
        date: '2026-07-05',
        reviewerName: 'Sina',
        reviewerEmail: 'sina@example.com',
      },
    ],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-01-25T10:00:00Z',
      updatedAt: '2026-07-05T15:00:00Z',
      barcode: '1034567890123',
      qrCode: 'https://example.com/qr/10',
    },
    images: [
      'https://avatar.iran.liara.run/public/24',
      'https://avatar.iran.liara.run/public/25',
    ],
    thumbnail: 'https://avatar.iran.liara.run/public/24',
  },

  {
    id: 11,
    title: 'Xbox Series X',
    description:
      'A powerful gaming console designed for high resolution gaming.',
    category: 'gaming',
    price: 499,
    discountPercentage: 6,
    rating: 4.8,
    stock: 22,
    tags: ['gaming', 'console', 'xbox'],
    brand: 'Microsoft',
    sku: 'MS-XBX-011',
    weight: 4450,
    dimensions: {
      width: 15.1,
      height: 30.1,
      depth: 15.1,
    },
    warrantyInformation: '1 year Microsoft warranty',
    shippingInformation: 'Ships within 2 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'Very powerful gaming console.',
        date: '2026-06-10',
        reviewerName: 'Milad',
        reviewerEmail: 'milad@example.com',
      },
    ],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-02-05T11:00:00Z',
      updatedAt: '2026-06-10T16:00:00Z',
      barcode: '1134567890123',
      qrCode: 'https://example.com/qr/11',
    },
    images: [
      'https://avatar.iran.liara.run/public/26',
      'https://avatar.iran.liara.run/public/27',
    ],
    thumbnail: 'https://avatar.iran.liara.run/public/26',
  },

  {
    id: 12,
    title: 'Canon EOS R6',
    description:
      'A professional mirrorless camera with advanced autofocus and image quality.',
    category: 'cameras',
    price: 2199,
    discountPercentage: 8,
    rating: 4.7,
    stock: 12,
    tags: ['camera', 'canon', 'photography'],
    brand: 'Canon',
    sku: 'CAN-R6-012',
    weight: 680,
    dimensions: {
      width: 13.8,
      height: 9.7,
      depth: 8.8,
    },
    warrantyInformation: '2 year Canon warranty',
    shippingInformation: 'Ships within 4 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'Fantastic camera for photography.',
        date: '2026-05-20',
        reviewerName: 'Farhad',
        reviewerEmail: 'farhad@example.com',
      },
    ],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-01-15T09:30:00Z',
      updatedAt: '2026-05-20T12:00:00Z',
      barcode: '1234567890124',
      qrCode: 'https://example.com/qr/12',
    },
    images: [
      'https://avatar.iran.liara.run/public/28',
      'https://avatar.iran.liara.run/public/29',
    ],
    thumbnail: 'https://avatar.iran.liara.run/public/28',
  },

  {
    id: 13,
    title: 'Logitech MX Master 3S',
    description:
      'An ergonomic wireless mouse designed for productivity and precision.',
    category: 'accessories',
    price: 99,
    discountPercentage: 10,
    rating: 4.6,
    stock: 54,
    tags: ['mouse', 'logitech', 'wireless'],
    brand: 'Logitech',
    sku: 'LOG-MX3S-013',
    weight: 141,
    dimensions: {
      width: 8.4,
      height: 12.5,
      depth: 5.1,
    },
    warrantyInformation: '2 year Logitech warranty',
    shippingInformation: 'Ships within 2 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'Very comfortable for long working sessions.',
        date: '2026-04-28',
        reviewerName: 'Yasin',
        reviewerEmail: 'yasin@example.com',
      },
    ],
    returnPolicy: '14 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-02-10T08:00:00Z',
      updatedAt: '2026-04-28T11:00:00Z',
      barcode: '1334567890124',
      qrCode: 'https://example.com/qr/13',
    },
    images: [
      'https://avatar.iran.liara.run/public/30',
      'https://avatar.iran.liara.run/public/31',
    ],
    thumbnail: 'https://avatar.iran.liara.run/public/30',
  },

  {
    id: 14,
    title: 'Mechanical Gaming Keyboard',
    description:
      'A mechanical keyboard with RGB lighting designed for gaming and typing.',
    category: 'accessories',
    price: 129,
    discountPercentage: 13,
    rating: 4.4,
    stock: 39,
    tags: ['keyboard', 'gaming', 'mechanical'],
    brand: 'Keychron',
    sku: 'KEY-KB-014',
    weight: 850,
    dimensions: {
      width: 35,
      height: 12,
      depth: 4,
    },
    warrantyInformation: '1 year manufacturer warranty',
    shippingInformation: 'Ships within 3 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 4,
        comment: 'Good keyboard with satisfying switches.',
        date: '2026-05-08',
        reviewerName: 'Amir',
        reviewerEmail: 'amir@example.com',
      },
    ],
    returnPolicy: '14 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-03-12T10:00:00Z',
      updatedAt: '2026-05-08T14:00:00Z',
      barcode: '1434567890124',
      qrCode: 'https://example.com/qr/14',
    },
    images: [
      'https://avatar.iran.liara.run/public/32',
      'https://avatar.iran.liara.run/public/33',
    ],
    thumbnail: 'https://avatar.iran.liara.run/public/32',
  },

  {
    id: 15,
    title: 'Nike Air Force 1',
    description:
      'Classic lifestyle sneakers with a comfortable design for everyday use.',
    category: 'shoes',
    price: 119,
    discountPercentage: 12,
    rating: 4.5,
    stock: 80,
    tags: ['shoes', 'nike', 'sneakers'],
    brand: 'Nike',
    sku: 'NKE-AF1-015',
    weight: 760,
    dimensions: {
      width: 12,
      height: 10,
      depth: 31,
    },
    warrantyInformation: '6 months manufacturer warranty',
    shippingInformation: 'Ships within 3 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'Classic and very comfortable shoes.',
        date: '2026-06-02',
        reviewerName: 'Reza',
        reviewerEmail: 'reza2@example.com',
      },
    ],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-02-22T12:00:00Z',
      updatedAt: '2026-06-02T15:00:00Z',
      barcode: '1534567890124',
      qrCode: 'https://example.com/qr/15',
    },
    images: [
      'https://avatar.iran.liara.run/public/34',
      'https://avatar.iran.liara.run/public/35',
    ],
    thumbnail: 'https://avatar.iran.liara.run/public/34',
  },

  {
    id: 16,
    title: 'Adidas Ultraboost',
    description:
      'Comfortable running shoes designed for daily training and active lifestyles.',
    category: 'shoes',
    price: 179,
    discountPercentage: 14,
    rating: 4.6,
    stock: 61,
    tags: ['shoes', 'adidas', 'running'],
    brand: 'Adidas',
    sku: 'ADI-UB-016',
    weight: 690,
    dimensions: {
      width: 11,
      height: 10,
      depth: 30,
    },
    warrantyInformation: '6 months manufacturer warranty',
    shippingInformation: 'Ships within 3 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'Very comfortable for running.',
        date: '2026-07-01',
        reviewerName: 'Navid',
        reviewerEmail: 'navid@example.com',
      },
    ],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-03-18T10:00:00Z',
      updatedAt: '2026-07-01T13:00:00Z',
      barcode: '1634567890124',
      qrCode: 'https://example.com/qr/16',
    },
    images: [
      'https://avatar.iran.liara.run/public/36',
      'https://avatar.iran.liara.run/public/37',
    ],
    thumbnail: 'https://avatar.iran.liara.run/public/36',
  },

  {
    id: 17,
    title: 'JBL Charge 5',
    description:
      'Portable Bluetooth speaker with powerful sound and long battery life.',
    category: 'audio',
    price: 179,
    discountPercentage: 9,
    rating: 4.5,
    stock: 43,
    tags: ['speaker', 'jbl', 'bluetooth'],
    brand: 'JBL',
    sku: 'JBL-C5-017',
    weight: 960,
    dimensions: {
      width: 22.3,
      height: 9.6,
      depth: 9.4,
    },
    warrantyInformation: '1 year JBL warranty',
    shippingInformation: 'Ships within 2 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 4,
        comment: 'Powerful sound for its size.',
        date: '2026-05-17',
        reviewerName: 'Soroush',
        reviewerEmail: 'soroush@example.com',
      },
    ],
    returnPolicy: '14 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-02-28T09:00:00Z',
      updatedAt: '2026-05-17T12:00:00Z',
      barcode: '1734567890124',
      qrCode: 'https://example.com/qr/17',
    },
    images: [
      'https://avatar.iran.liara.run/public/38',
      'https://avatar.iran.liara.run/public/39',
    ],
    thumbnail: 'https://avatar.iran.liara.run/public/38',
  },

  {
    id: 18,
    title: 'Kindle Paperwhite',
    description:
      'A compact e-reader with a high resolution display and adjustable lighting.',
    category: 'tablets',
    price: 159,
    discountPercentage: 7,
    rating: 4.7,
    stock: 27,
    tags: ['kindle', 'ebook', 'amazon'],
    brand: 'Amazon',
    sku: 'AMZ-KPW-018',
    weight: 205,
    dimensions: {
      width: 12.5,
      height: 17.4,
      depth: 0.8,
    },
    warrantyInformation: '1 year Amazon warranty',
    shippingInformation: 'Ships within 3 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'Excellent screen for reading books.',
        date: '2026-06-22',
        reviewerName: 'Mahan',
        reviewerEmail: 'mahan@example.com',
      },
    ],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-01-30T11:00:00Z',
      updatedAt: '2026-06-22T14:00:00Z',
      barcode: '1834567890124',
      qrCode: 'https://example.com/qr/18',
    },
    images: [
      'https://avatar.iran.liara.run/public/40',
      'https://avatar.iran.liara.run/public/41',
    ],
    thumbnail: 'https://avatar.iran.liara.run/public/40',
  },

  {
    id: 19,
    title: 'Xiaomi Robot Vacuum',
    description:
      'A smart robot vacuum cleaner with automatic cleaning and navigation.',
    category: 'home-appliances',
    price: 399,
    discountPercentage: 15,
    rating: 4.3,
    stock: 19,
    tags: ['robot', 'vacuum', 'xiaomi', 'smart-home'],
    brand: 'Xiaomi',
    sku: 'XIA-RV-019',
    weight: 3500,
    dimensions: {
      width: 35,
      height: 35,
      depth: 9.5,
    },
    warrantyInformation: '1 year Xiaomi warranty',
    shippingInformation: 'Ships within 4 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 4,
        comment: 'Works well and saves a lot of time.',
        date: '2026-07-10',
        reviewerName: 'Ehsan',
        reviewerEmail: 'ehsan@example.com',
      },
    ],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-02-12T10:30:00Z',
      updatedAt: '2026-07-10T13:30:00Z',
      barcode: '1934567890124',
      qrCode: 'https://example.com/qr/19',
    },
    images: [
      'https://avatar.iran.liara.run/public/42',
      'https://avatar.iran.liara.run/public/43',
    ],
    thumbnail: 'https://avatar.iran.liara.run/public/42',
  },

  {
    id: 20,
    title: 'Dyson Air Purifier',
    description:
      'A modern air purifier designed to improve indoor air quality.',
    category: 'home-appliances',
    price: 549,
    discountPercentage: 10,
    rating: 4.6,
    stock: 14,
    tags: ['dyson', 'air-purifier', 'home'],
    brand: 'Dyson',
    sku: 'DYS-AP-020',
    weight: 4200,
    dimensions: {
      width: 22,
      height: 83,
      depth: 22,
    },
    warrantyInformation: '2 year Dyson warranty',
    shippingInformation: 'Ships within 4 business days',
    availabilityStatus: 'In Stock',
    reviews: [
      {
        rating: 5,
        comment: 'Quiet and effective air purifier.',
        date: '2026-08-05',
        reviewerName: 'Shayan',
        reviewerEmail: 'shayan@example.com',
      },
    ],
    returnPolicy: '30 days return policy',
    minimumOrderQuantity: 1,
    meta: {
      createdAt: '2026-03-25T09:00:00Z',
      updatedAt: '2026-08-05T12:30:00Z',
      barcode: '2034567890124',
      qrCode: 'https://example.com/qr/20',
    },
    images: [
      'https://avatar.iran.liara.run/public/44',
      'https://avatar.iran.liara.run/public/45',
    ],
    thumbnail: 'https://avatar.iran.liara.run/public/44',
  },
];
